### ISSUE TITLE
You spelt gain wrong

### ISSUE THREAD

**Issue by webmaster-exit-1** [MMRLApp/mmrl_install_tools#17]
lol, fix this ![Screenshot_2024-06-04-06-04-50-02_fd4950220a21ab37e4313904dcdb5acb.jpg](https://github.com/DerGoogler/mmrl_install_tools/assets/98633966/398805a2-aee9-4908-9423-faf8a6c44eed)

you put **grain**

**Comment by webmaster-exit-1** [comment]
to **grain ** access

lol

**Comment by webmaster-exit-1** [comment]
to **grain** access

lol

**Comment by webmaster-exit-1** [comment]
It also still broken![Screenshot_2024-06-04-06-35-05-00_fd4950220a21ab37e4313904dcdb5acb.jpg](https://github.com/DerGoogler/mmrl_install_tools/assets/98633966/45a4147b-f0c3-4bfc-912d-1363aade065f)

**Comment by webmaster-exit-1** [comment]
![Screenshot_2024-06-04-06-38-02-90_fd4950220a21ab37e4313904dcdb5acb.jpg](https://github.com/DerGoogler/mmrl_install_tools/assets/98633966/55ddf74e-cab8-4111-a960-6d783590bf1e)

**Comment by webmaster-exit-1** [comment]
I edited the explore install script. After, it works. But still says error after successful install. Here are the screenshots
![Screenshot_2024-06-04-06-42-03-38_fd4950220a21ab37e4313904dcdb5acb.jpg](https://github.com/DerGoogler/mmrl_install_tools/assets/98633966/b8f90e15-101d-4202-ab57-7a42c9dd6d8a)

![Screenshot_2024-06-04-06-42-30-94_fd4950220a21ab37e4313904dcdb5acb.jpg](https://github.com/DerGoogler/mmrl_install_tools/assets/98633966/e9634b72-84d2-441c-ba98-58393651a41b)

**Comment by webmaster-exit-1** [comment]
I have no clue what is calling that "**Internal error** message.

**Comment by DerGoogler** [comment]
> I have no clue what is calling that "**Internal error**" message.

that it usually exit code 500

**Comment by DerGoogler** [comment]
Spelling issue has been fixed

**Comment by webmaster-exit-1** [comment]
> Spelling issue has been fixed

happens to me all the time. One way to fix that in the future is to add spell check as a ci job in your workflow to automate the entire process. Not sure if you use this github feature. It's not too hard to figure out.

**Comment by DerGoogler** [comment]
That's actually a MMRL problem. It may the try-catch in the terminal plugin
